listen_addresses = ['[::1]:53001', '127.0.0.1:53001']
max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
require_dnssec = true
require_nolog = false
require_nofilter = true
force_tcp = false
timeout = 2500
keepalive = 30
blocked_query_response = 'refused'
log_level = 2
log_file = 'dnscrypt-proxy.log'
cert_refresh_delay = 240
bootstrap_resolvers = ['208.67.222.222:5353', '8.8.4.4:53', '9.9.9.11:9953']
ignore_system_dns = false
netprobe_timeout = 60
block_ipv6 = false
cloaking_rules = 'cloaking-rules.txt'
cache = true
cache_size = 512
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600
[query_log]
  file = 'query.log'
  format = 'tsv'
  ignored_qtypes = ['DNSKEY', 'NS', 'DS']
[sources]
  [sources.'public-resolvers']
  urls = ['https://cdn.jsdelivr.net/gh/DNSCrypt/dnscrypt-resolvers/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md', 'https://cdn.statically.io/gh/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://ghcdn.rawgit.org/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix='' 
